Add disable samba option (NVRAM)

diff --git a/package/dni/samba-scripts/files/samba.init b/package/dni/samba-scripts/files/samba.init
--- a/package/dni/samba-scripts/files/samba.init
+++ b/package/dni/samba-scripts/files/samba.init
@@ -2,53 +2,63 @@
 
 START=86
 
+PATH=/bin:/sbin:/usr/bin:/usr/sbin
+CONFIG=/bin/config
+SAMBA_DISABLED=$($CONFIG get samba_disable)
+
 start()
 {
-    DEFAULT=/etc/default/samba
-    RUN_D=/var/run/samba
-    SMB_CONF_DIR=/tmp/samba
-    SYS_CONF_DIR=/tmp/config
-    PRIVATE_DIR=/tmp/private
-    SMBD_PID_F=$RUN_D/smbd.pid
-    SMB_PASSWD_DIR=/tmp/smbpasswd
-    [ -f $DEFAULT ] && . $DEFAULT
+	# Check if Samba is disabled
+	if [ "$SAMBA_DISABLED" = "1" ]; then
+	echo "Error: Samba is disabled. Enable Samba (nvram set samba_disable=0)."
+		exit 1
+	fi
 
-    mkdir -p /var/log/samba
-    #mount -t tmpfs tmpfs /home -o size=64K
-    mkdir -p $SMB_CONF_DIR
-    cp -f /etc/config/samba/smb.conf $SMB_CONF_DIR
-    cp -f /etc/config/samba/lowcase.dat $SMB_CONF_DIR
-    cp -f /etc/config/samba/upcase.dat $SMB_CONF_DIR
-    cp -f /etc/config/samba/valid.dat $SMB_CONF_DIR
-    mkdir -p $SYS_CONF_DIR
-    cp -f /usr/config/passwd $SYS_CONF_DIR
-    cp -f /usr/config/group $SYS_CONF_DIR
-    cp -f /usr/config/shadow $SYS_CONF_DIR
-    mkdir -p $PRIVATE_DIR
-    mkdir -p $RUN_D
+	DEFAULT=/etc/default/samba
+	RUN_D=/var/run/samba
+	SMB_CONF_DIR=/tmp/samba
+	SYS_CONF_DIR=/tmp/config
+	PRIVATE_DIR=/tmp/private
+	SMBD_PID_F=$RUN_D/smbd.pid
+	SMB_PASSWD_DIR=/tmp/smbpasswd
+	[ -f $DEFAULT ] && . $DEFAULT
 
-    # create users, groups
-    update_user
+	mkdir -p /var/log/samba
+	#mount -t tmpfs tmpfs /home -o size=64K
+	mkdir -p $SMB_CONF_DIR
+	cp -f /etc/config/samba/smb.conf $SMB_CONF_DIR
+	cp -f /etc/config/samba/lowcase.dat $SMB_CONF_DIR
+	cp -f /etc/config/samba/upcase.dat $SMB_CONF_DIR
+	cp -f /etc/config/samba/valid.dat $SMB_CONF_DIR
+	mkdir -p $SYS_CONF_DIR
+	cp -f /usr/config/passwd $SYS_CONF_DIR
+	cp -f /usr/config/group $SYS_CONF_DIR
+	cp -f /usr/config/shadow $SYS_CONF_DIR
+	mkdir -p $PRIVATE_DIR
+	mkdir -p $RUN_D
 
-    # detect SATA disk
-    /usr/sbin/detectSATA start
+	# create users, groups
+	update_user
 
-    # update smb.conf and start samba if needed
-    /etc/init.d/dbus start
-    /etc/init.d/avahi-daemon start
-    /usr/sbin/update_smb.sh
+	# detect SATA disk
+	/usr/sbin/detectSATA start
+
+	# update smb.conf and start samba if needed
+	/etc/init.d/dbus start
+	/etc/init.d/avahi-daemon start
+	/usr/sbin/update_smb.sh
 }
 
 stop() {
-    killall -9 smbd
-    killall -9 nmbd
-    /etc/init.d/avahi-daemon stop
-    /etc/init.d/dbus stop
+	killall -9 smbd
+	killall -9 nmbd
+	/etc/init.d/avahi-daemon stop
+	/etc/init.d/dbus stop
 }
 
 boot() {
-    start &
-    /etc/init.d/kcode boot
+	start &
+	/etc/init.d/kcode boot
 }
 
 [ "$1" = "start" ] && start
